global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'together-app'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:30000']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9097']